### ISSUE TITLE
No season 4 cosmetics

### ISSUE THREAD

**Issue by SlimeChannel** [spicyboys/drg-completionist#110]
I found this great site by scrolling reddit and started to fill it in, but as I went through I couldn't find any season 4 skins (maybe overclocks, I'm not sure) and maybe even season 3 skins are missing (also only 3 skins and paintjobs for bosco) so I would like to know whether there will be season 3-4 content or not?

**Comment by rob0rt** [comment]
Hmm.. I was pretty sure @NichCodes had added Season 4 content (and @nojonqs Season 3 before that). Do you have an example of an item that's missing? 

If we are missing things, it'll just a matter of effort to get them in. It's time consuming to decompile the game to get the asset IDs and icons so it does tend to get out of date towards the beginning of the seasons.

**Comment by SlimeChannel** [comment]
For example I have infected weapon framework. It's performance pass skin but it isn't mentioned on the site nor the fandom wiki
And there are items from previous seasons marked as performance pass skins even though they're already not (MilSpec frameworks in example)
I wrote this whole issue down because on the read.me in upcoming changes there is stated, that "None are planned right now"

**Comment by NichCodes** [comment]
I've only added the Season 4 OCs so far. I believe the Season 4 performance pass weapon frameworks, cosmetics, and paint jobs still need to be datamined and added manually, which we haven't done yet since we don't have pictures for all of them yet.

**Comment by SlimeChannel** [comment]
Ok then, ty for responses!
