### ISSUE TITLE
Netlify Bandwidth almost exhausted

### ISSUE THREAD

**Issue by rob0rt** [spicyboys/drg-completionist#112]
> This issue is half notification, half action item.

Our Netlify Bandwidth has almost been exhausted at less than 50% of the way through the month. I don't pay for hosting and use Netlify's free tier, which allocates us to 100Gb of bandwidth a month. We only have a few hundred users a day, so this seems like a lot of data per user, and indeed by looking at data transfer in the console it's trivially possible for a session to request nearly 100mb of assets. The issue seems to be twofold:

1) Images don't appear to be cached in the browser across sessions for some reason. Perhaps they're missing a header?
1) Images are not properly optimized and are far larger than necessary.

I'm working on a fix that's summarily described as a rewrite: we've outgrown our roots from create-react-app (we actually did that, like, a _long_ time ago when we threw `craco` into the mix) and need to find a better structural solution. I've settled on Nuxt for reasons I'll explain in the PR when it's ready. As part of this rewrite, I hope to move us to the static host we should have used the whole time: Github Pages.

In the meantime, it's not just likely but entirely expected that **the site will go dark as soon as tomorrow** as we finish chewing through the rest of our bandwidth. There's very little I can do about this without incurring tangible costs which I'm not comfortable paying for without financial support (extra bandwidth on Netlify is expensive at $55/100Gb, which we'd likely go through twice over). I'll continue to work on the rewrite and hope to have it completed by end of week, but there's an extremely high chance there will be a few days between now and when that's done and deployed that the site will be offline.

**Comment by Marian-The-Only** [comment]
So this is the reason the site is down atm? I fully understand that paying for it is not an option and I am looking forward to August, when it is presumably going to be available again.

**Comment by rob0rt** [comment]
Site is _sorta_ back up after a re-build. Features are missing and it's rough around the edges but it's scalable and it's up.
