### ISSUE TITLE
Current Season Cosmetics

### ISSUE THREAD

**Issue by SwiperDaSniper** [spicyboys/drg-completionist#124]
Just wondering when the current seasons cosmetics such as weapon frames and armor skins will be added. 

I appreciate the work you put this site!

**Comment by rob0rt** [comment]
Timelines are kind of wishy-washy 'round these parts; We've had a remarkable burst of productivity with the redesign but haven't done any data mining as of late for the newest content. It's possible I might do that this week, but have some travel coming up and might not get to it before then. We'll create a new tagged release and close this issue when the new content has been added, though

**Comment by rob0rt** [comment]
Tracking in #133
