### ISSUE TITLE
Save analyzor error

### ISSUE THREAD

**Issue by Bujdosf** [spicyboys/drg-completionist#125]
'File Error: String length of (788529152) invalid, likely a read error.', or at least thats what i believe should be the problem.
Uploaded my savefile here: [](https://nextcloud05.webo.cloud/s/GCc2jop4i5CSQJL)
password is 5/ec2I>i1N

**Comment by rob0rt** [comment]
Thanks for the report; it looks like you didn't actually include a link to a save file, would you mind trying to attach that again?

**Comment by Bujdosf** [comment]
[Sorry, this should be it.](https://nextcloud05.webo.cloud/s/GCc2jop4i5CSQJL)

**Comment by rob0rt** [comment]
Thanks! Confirmed I'm able to reproduce, and will take a look after work

**Comment by rob0rt** [comment]
I found the bug and have it fixed in the save parser. I'll need to update the save parser package and then update the dependency in this project.

**Comment by rob0rt** [comment]
Fixed
