### ISSUE TITLE
Stuck in an endless analyzing loop

### ISSUE THREAD

**Issue by chaoticnecropunk** [spicyboys/drg-completionist#138]
Analyze save file gets stuck in an "Analyzing" loop. The save file does not load past this point at all.
[Here is my Steam save file](https://github.com/spicyboys/drg-completionist/files/12316522/76561198071953664_Player.zip)
![Screenshot_20230810_152209_Chrome](https://github.com/spicyboys/drg-completionist/assets/141958724/87462a30-f6a0-4654-9e91-5a74ad87c62b)

I tried using different browsers and tried using my phone, no luck :(

**Comment by rob0rt** [comment]
Sorry for the delayed response and thanks for the report/ save file. I'm currently on holiday but will be able to look into this sometime in the next few days.

**Comment by chaoticnecropunk** [comment]
No worries! Thanks for the heads up,  enjoy your holiday 😁

**Comment by rob0rt** [comment]
Should be fixed!

**Comment by chaoticnecropunk** [comment]
Awesome thank you so much, you're amazing. Seriously. Rock and stone! 🍻

**Comment by pkol777** [comment]
I'm having this same issue as of 12/3/23, curious if november update broke it again
