### ISSUE TITLE
Analyze Save not Working

### ISSUE THREAD

**Issue by pkol777** [spicyboys/drg-completionist#163]
Analyze save file gets stuck in an "Analyzing" loop. Saw this has been an issue before, wondering if november update broke the functionality.

**Comment by rob0rt** [comment]
Thanks for the report; do you mind sharing your save file so I can reproduce?

**Comment by lucidobservor** [comment]
[76561198064990852_Player.zip](https://github.com/spicyboys/drg-completionist/files/13604644/76561198064990852_Player.zip)

Came to report the same issue, here's another save file in case that helps.

**Comment by Larax1011** [comment]
Not sure if my issue is the same but analyzing also doesn't work for me...
When I select a file nothing happens. Here's the console log and my save
![image](https://github.com/spicyboys/drg-completionist/assets/37920057/b0658516-a94d-402d-9028-7232ef65cab1)

[76561198026251469_Player.zip](https://github.com/spicyboys/drg-completionist/files/13678572/76561198026251469_Player.zip)

**Comment by rob0rt** [comment]
Thanks for the reports and save files y'all; it seems like Ghost Ship added some new types to the save file that I have to add to the parser. I haven't had too much of an opportunity to get into this to fix it but I'll try to take a quick look this weekend

**Comment by rob0rt** [comment]
Fixed in the newest version, which should be deploying automatically. Sorry for the trouble!
