### ISSUE TITLE
Please update to current game version (Season 5)

### ISSUE THREAD

**Issue by greezlu** [spicyboys/drg-completionist#206]
[Season 05: Drilling Deeper](https://deeprockgalactic.wiki.gg/wiki/Season_05:_Drilling_Deeper)

13.06.2024 New season was added together with new items. Please update the service.

> New Overclocks
> Added 12 new Overclocks (one for each primary weapon), plus one rework of an existing Overclock.
> 
> "Lead Storm" Powered Minigun: Rotary Overdrive
> "Thunderhead" Heavy Autocannon: Mortar Rounds
> "Hurricane" Guided Rocket System: Cluster Charges
> "Deepcore GK2": Burst Fire
> "M1000 Classic": Marked for Death
> "DRAK-25 Plasma Carbine": Conductive Thermals
> "Warthog" Auto 210: Pump Action
> "Stubby" Voltaic SMG: Hyperalloy Assembly
> [Rework] "Stubby" Voltaic SMG: Micro-Conductor Add-On
> "LOK-1 Smart Rifle": SmЯt Trigger OS™
> "CRSPR Flamethrower": Scorching Tide
> "Cryo Cannon": Crystal Nucleation
> "Corrosive Sludge Pump": Combustive Goo Mix

**Comment by rob0rt** [comment]
I will be honest: this is not likely to be done unless someone else would like to contribute the necessary changes to make it happen. I haven't played DRG in a hot minute and don't have the time nor energy to actively add new content or maintain this site outside of reviewing PRs. 

If anyone would like to contribute, it's actively welcomed. The site's data layout is pretty approachable, it just requires a bit of digging around in the game files to get some UUIDs and collecting images. I'll happily approve PRs which do so.
