### ISSUE TITLE
Add content from U36 (Season 2)

### ISSUE THREAD

**Issue by dpanter** [spicyboys/drg-completionist#68]
Season 2 is out with new stuff, savefile no longer compatible.
https://deeprockgalactic.fandom.com/wiki/Season_02:_Rival_Escalation

Presumably #58 was sorted as DRG Completionist worked before Season 2, but it's possible the Unreal Engine upgrade also changed the savefile format.

**Comment by rob0rt** [comment]
We intend to update the site for new content (I believe we're also missing Season 1 content). I need to dig in the game files again to get the new item IDs and then spend another day or two (and hopefully no more) debugging what changed in the save file format that broke the parser 😥

Both @Fleckeri and I work full time and this has always been a bit of a passion project on the side, and we haven't had much time/ energy to invest into the updates, unfortunately. We hope to get to it soon; maybe the extra day this weekend will be an opportunity for us to day so 🙂

**Comment by rob0rt** [comment]
Good news, I made a bit of progress and got the save file parser working again! We still need to add the new content, but that's the harder problem solved

**Comment by rob0rt** [comment]
Getting the new content IDs is something I plan to look at this weekend :) I'll try to document a short tutorial of how I'm doing so when I do so others can contribute later
