### ISSUE TITLE
Unable to load save file (MulticastInlineDelegateProperty)

### ISSUE THREAD

**Issue by Larax1011** [spicyboys/drg-completionist#72]
When i try to load a save file i get this error in the console
![image](https://user-images.githubusercontent.com/37920057/181602239-53b427dc-5fc7-4c6c-9505-7050020d49e2.png)
Tried doing different saves and still doesn't work.

**Comment by rob0rt** [comment]
Interesting, I thought we had fixed that issue. I'm able to reproduce though so perhaps not. I'll take a look soon and see if I can't figure out what's going on

**Comment by rob0rt** [comment]
This has been resolved, it was fixed but never deployed
