### ISSUE TITLE
Add content from U37 (Season 3)

### ISSUE THREAD

**Issue by dpanter** [spicyboys/drg-completionist#76]
Well, another season is out. 
https://deeprockgalactic.fandom.com/wiki/Season_03:_Plaguefall

Any chance this project can be updated? The website seems kinda stuck on U34.

**Comment by nojonqs** [comment]
I'm currently working on adding the new weapons and overclocks. But the save file parser does not seem to give us the ids of the new overclocks and I can't figure out why it shouldn't.
@rob0rt @Fleckeri Am I missing something or is the save file parser not yet capable of parsing new overclocks (really doubt it though)?

**Comment by rob0rt** [comment]
Resolved as of #78
