### ISSUE TITLE
Missing Framework for Secondaries

### ISSUE THREAD

**Issue by ftckayes** [spicyboys/drg-completionist#87]
First - thanks for the massive update! Glad to see this is still supported!

Second - I noticed that the Waster framework for the secondary weapons introduced in season two isn't listed. TIA!

![image](https://user-images.githubusercontent.com/122426341/211723300-d399167c-44b7-451f-88b9-a8f6fd952121.png)

**Comment by nojonqs** [comment]
Oh, I can see why that happened. Thank you for the heads up!
I will get on it and it should be fixed in a bit.
