### ISSUE TITLE
Unobtainable Victory Moves

### ISSUE THREAD

**Issue by justacer** [spicyboys/drg-completionist#90]
Currently there's no legitimate way to obtain the Feeding Lootbug and Salt victory moves, which are present in the respective section of the app.

![image](https://user-images.githubusercontent.com/122628497/212370346-39658666-097b-4416-8811-b11953c638ba.png)

**Comment by nojonqs** [comment]
Thanks for the info, this must have to do with some IDs being mixed up, just like the frameworks. I'll look into it.

**Comment by nojonqs** [comment]
This is interesting, they are listed the same way in the game files but according to the wiki they are indeed not obtainable through lost packs.
Since we want to only track freely obtainable items in DRG Completionist, I will remove them from the tab.

**Comment by nojonqs** [comment]
This is interesting, they are listed the same way in the game files but according to the wiki they are indeed not obtainable through lost packs.
Since we want to only track freely obtainable items in DRG Completionist, I will remove them from the tab.
