### ISSUE TITLE
Season 1 & 2 Cosmetics Import

### ISSUE THREAD

**Issue by justacer** [spicyboys/drg-completionist#91]
The app doesn't import cosmetics added in Seasons 1 and 2. I believe this issue has to do with the fact that I unlocked these items through their respective Performance Passes instead of forging them after they were added to the Matrix Core item pool.

**Comment by nojonqs** [comment]
Yes, when you unlock items trough the season, they will not show up in your unlocked matrix cores in the game. The check for obtained cosmetics should happen for the actual item id and not it's matrix core id.

I'll look into it.

**Comment by nojonqs** [comment]
I need to investigate where and how the cosmetics are saved in the savefile in this special case.
Do you mind sending me your savefile?

**Comment by justacer** [comment]
Thank you very much for quickly fixing all the issues I reported! I'm sorry I couldn't provide you with my save file in time. :(

**Comment by nojonqs** [comment]
It's fine, I was a little confused but I unlocked the season cosmetics through the performance pass as well, so I could just use mine.
